display_errors=Off
log_errors=On
expose_php=Off
variables_order=EGPCS

upload_max_filesize=64M
post_max_size=64M
max_file_uploads=20

opcache.enable=1
opcache.enable_cli=0
opcache.validate_timestamps=0
opcache.max_accelerated_files=20000
opcache.memory_consumption=128
opcache.interned_strings_buffer=16
