server {
    listen 80;
    server_name _;

    root /app;
    index index.php index.html;

    client_max_body_size 64m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT /app;
        fastcgi_pass app:9000;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot|html)$ {
        try_files $uri =404;
        access_log off;
        expires 1h;
    }
}
